export const starterAssignments = [
  {
    number: "01",
    slug: "mini-book-list",
    title: "Mini Book List",
    description:
      "Connect a React frontend to book data provided by a Node.js server.",
    stack: "React · Node.js · Express",
    category: "fullstack",
    learn: "Client–Server Communication / REST API",
    download: "/advance/download/mini-book-list.zip",
  },
  {
    number: "02",
    slug: "student-registration",
    title: "Student Registration",
    description:
      "Make student registrations remain available after the server restarts.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "MySQL & Database Persistence",
    download: "/advance/download/student-registration.zip",
  },
  {
    number: "03",
    slug: "secure-student-registration",
    title: "Secure Student Registration",
    description:
      "Store student account information without saving the original password.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Password Hashing",
    download: "/advance/download/secure-student-registration.zip",
  },
  {
    number: "04",
    slug: "logged-in-user",
    title: "Logged-In User",
    description:
      "Let the backend identify which student is requesting their profile.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Authentication / JWT",
    download: "/advance/download/logged-in-user.zip",
  },
  {
    number: "05",
    slug: "private-notes",
    title: "Private Notes",
    description:
      "Return only the private notes belonging to the user making the request.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Resource Authorization / Ownership",
    download: "/advance/download/private-notes.zip",
  },
  {
    number: "06",
    slug: "product-manager",
    title: "Product Manager",
    description:
      "Enforce different product access rules for Admin and Normal User accounts.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "RBAC / Role-Based Authorization",
    download: "/advance/download/product-manager.zip",
  },
  {
    number: "07",
    slug: "event-registration",
    title: "Event Registration",
    description:
      "Make sure incoming registration data is correct before it is stored.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Backend Validation",
    download: "/advance/download/event-registration.zip",
  },
  {
    number: "08",
    slug: "bank-account-api",
    title: "Bank Account API",
    description:
      "Replace repeated failure-handling code with one maintainable approach.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Centralized Error Handling",
    download: "/advance/download/bank-account-api.zip",
  },
  {
    number: "09",
    slug: "online-store-orders",
    title: "Online Store Orders",
    description:
      "Return complete order details from separately stored customer, product, and order data.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "SQL JOINs & Relationships",
    download: "/advance/download/online-store-orders.zip",
  },
  {
    number: "10",
    slug: "product-search",
    title: "Product Search",
    description:
      "Make product name search stay fast across a very large catalog.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Database Search Performance",
    download: "/advance/download/product-search.zip",
  },
  {
    number: "11",
    slug: "movie-seat-booking-system",
    title: "Movie Seat Booking System",
    description:
      "Make sure two customers can never both end up with the same seat when they book at the same time.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    learn: "Data Consistency Under Concurrent Requests",
    download: "/advance/download/movie-seat-booking-system.zip",
  },
  {
    number: "12",
    slug: "admin-dashboard",
    title: "Admin Dashboard",
    description:
      "Fix a small admin dashboard where the same UI keeps getting copy-pasted every time it needs to change.",
    stack: "React",
    category: "frontend",
    learn: "Maintainable UI Structure",
    download: "/advance/download/admin-dashboard.zip",
  },
  {
    number: "13",
    slug: "status-dashboard",
    title: "Status Dashboard",
    description:
      "Fix a small ops dashboard whose panels each reimplement the same loading, error, and retry logic.",
    stack: "React",
    category: "frontend",
    learn: "Reusable Stateful Behavior",
    download: "/advance/download/status-dashboard.zip",
  },
  {
    number: "14",
    slug: "mini-storefront",
    title: "Mini Storefront",
    description:
      "Untangle a shopping cart app where unrelated components have to forward cart data they never use.",
    stack: "React",
    category: "frontend",
    learn: "Shared Application State",
    download: "/advance/download/mini-storefront.zip",
  },
  {
    number: "15",
    slug: "customer-dashboard",
    title: "Customer Dashboard",
    description:
      "Fix a customer dashboard that gives users no useful feedback while loading, on failure, or when there's nothing to show.",
    stack: "React · Node.js · Express",
    category: "fullstack",
    learn: "Server Data Handling",
    download: "/advance/download/customer-dashboard.zip",
  },
  {
    number: "16",
    slug: "product-dashboard",
    title: "Product Dashboard",
    description:
      "Speed up a product dashboard that redoes expensive work every time something on the page changes — even when nothing relevant did.",
    stack: "React",
    category: "frontend",
    learn: "Efficient Rendering",
    download: "/advance/download/product-dashboard.zip",
  },
  {
    number: "17",
    slug: "support-ticket-dashboard",
    title: "Support Ticket Dashboard",
    description:
      "Fix a support ticket dashboard that gets stuck loading forever on failure and goes silently blank when there's nothing to show.",
    stack: "React · Node.js · Express",
    category: "fullstack",
    learn: "Server Data Handling",
    download: "/advance/download/support-ticket-dashboard.zip",
  },
];
