export const starterAssignments = [
  {
    number: "01",
    slug: "mini-book-list",
    title: "Mini Book List",
    description:
      "Connect a React frontend to book data provided by a Node.js server.",
    stack: "React · Node.js · Express",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "rest-api-fundamentals",
    learn: "Client–Server Communication / REST API",
    download: "/advance/download/mini-book-list.zip",
  },
  {
    number: "02",
    slug: "student-registration",
    title: "Student Registration",
    description:
      "Make student registrations remain available after the server restarts.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "database",
    technology: "mysql",
    topic: "mysql-persistence",
    learn: "MySQL & Database Persistence",
    download: "/advance/download/student-registration.zip",
  },
  {
    number: "03",
    slug: "secure-student-registration",
    title: "Secure Student Registration",
    description:
      "Store student account information without saving the original password.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "password-security",
    learn: "Password Hashing",
    download: "/advance/download/secure-student-registration.zip",
  },
  {
    number: "04",
    slug: "logged-in-user",
    title: "Logged-In User",
    description:
      "Let the backend identify which student is requesting their profile.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "authentication",
    learn: "Authentication / JWT",
    download: "/advance/download/logged-in-user.zip",
  },
  {
    number: "05",
    slug: "private-notes",
    title: "Private Notes",
    description:
      "Return only the private notes belonging to the user making the request.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "resource-authorization",
    learn: "Resource Authorization / Ownership",
    download: "/advance/download/private-notes.zip",
  },
  {
    number: "06",
    slug: "product-manager",
    title: "Product Manager",
    description:
      "Enforce different product access rules for Admin and Normal User accounts.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "role-based-authorization",
    learn: "RBAC / Role-Based Authorization",
    download: "/advance/download/product-manager.zip",
  },
  {
    number: "07",
    slug: "event-registration",
    title: "Event Registration",
    description:
      "Make sure incoming registration data is correct before it is stored.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "request-validation",
    learn: "Backend Validation",
    download: "/advance/download/event-registration.zip",
  },
  {
    number: "08",
    slug: "bank-account-api",
    title: "Bank Account API",
    description:
      "Replace repeated failure-handling code with one maintainable approach.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "backend",
    technology: "nodejs",
    topic: "centralized-error-handling",
    learn: "Centralized Error Handling",
    download: "/advance/download/bank-account-api.zip",
  },
  {
    number: "09",
    slug: "online-store-orders",
    title: "Online Store Orders",
    description:
      "Return complete order details from separately stored customer, product, and order data.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "database",
    technology: "mysql",
    topic: "relationships-and-joins",
    learn: "SQL JOINs & Relationships",
    download: "/advance/download/online-store-orders.zip",
  },
  {
    number: "10",
    slug: "product-search",
    title: "Product Search",
    description:
      "Make product name search stay fast across a very large catalog.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "database",
    technology: "mysql",
    topic: "query-optimization",
    learn: "Database Search Performance",
    download: "/advance/download/product-search.zip",
  },
  {
    number: "11",
    slug: "movie-seat-booking-system",
    title: "Movie Seat Booking System",
    description:
      "Make sure two customers can never both end up with the same seat when they book at the same time.",
    stack: "React · Node.js · Express · MySQL",
    category: "fullstack",
    area: "database",
    technology: "mysql",
    topic: "transactions-and-concurrency",
    learn: "Data Consistency Under Concurrent Requests",
    download: "/advance/download/movie-seat-booking-system.zip",
  },
  {
    number: "12",
    slug: "admin-dashboard",
    title: "Admin Dashboard",
    description:
      "Fix a small admin dashboard where the same UI keeps getting copy-pasted every time it needs to change.",
    stack: "React",
    category: "frontend",
    area: "frontend",
    technology: "react",
    topic: "component-architecture",
    learn: "Maintainable UI Structure",
    download: "/advance/download/admin-dashboard.zip",
  },
  {
    number: "13",
    slug: "status-dashboard",
    title: "Status Dashboard",
    description:
      "Fix a small ops dashboard whose panels each reimplement the same loading, error, and retry logic.",
    stack: "React",
    category: "frontend",
    area: "frontend",
    technology: "react",
    topic: "custom-hooks",
    learn: "Reusable Stateful Behavior",
    download: "/advance/download/status-dashboard.zip",
  },
  {
    number: "14",
    slug: "mini-storefront",
    title: "Mini Storefront",
    description:
      "Untangle a shopping cart app where unrelated components have to forward cart data they never use.",
    stack: "React",
    category: "frontend",
    area: "frontend",
    technology: "react",
    topic: "state-management",
    learn: "Shared Application State",
    download: "/advance/download/mini-storefront.zip",
  },
  {
    number: "15",
    slug: "customer-dashboard",
    title: "Customer Dashboard",
    description:
      "Fix a customer dashboard that gives users no useful feedback while loading, on failure, or when there's nothing to show.",
    stack: "React · Node.js · Express",
    category: "fullstack",
    area: "frontend",
    technology: "react",
    topic: "api-fetching-and-ui-states",
    learn: "Server Data Handling",
    download: "/advance/download/customer-dashboard.zip",
  },
  {
    number: "16",
    slug: "product-dashboard",
    title: "Product Dashboard",
    description:
      "Speed up a product dashboard that redoes expensive work every time something on the page changes — even when nothing relevant did.",
    stack: "React",
    category: "frontend",
    area: "frontend",
    technology: "react",
    topic: "performance-optimization",
    learn: "Efficient Rendering",
    download: "/advance/download/product-dashboard.zip",
  },
  {
    number: "17",
    slug: "support-ticket-dashboard",
    title: "Support Ticket Dashboard",
    description:
      "Fix a support ticket dashboard that gets stuck loading forever on failure and goes silently blank when there's nothing to show.",
    stack: "React · Node.js · Express",
    category: "fullstack",
    area: "frontend",
    technology: "react",
    topic: "api-fetching-and-ui-states",
    learn: "Server Data Handling",
    download: "/advance/download/support-ticket-dashboard.zip",
  },
];


export const assignmentCatalog = [
  {
    slug: "frontend",
    title: "Frontend",
    description: "Build maintainable, responsive user interfaces.",
    technologies: [{
      slug: "react",
      title: "React",
      description: "Practice React architecture, state, data fetching, and performance.",
      topics: [
        { level: "advanced", slug: "component-architecture", title: "Component Architecture" },
        { level: "advanced", slug: "custom-hooks", title: "Custom Hooks" },
        { level: "advanced", slug: "state-management", title: "State Management" },
        { level: "advanced", slug: "api-fetching-and-ui-states", title: "API Fetching and UI States" },
        { level: "advanced", slug: "performance-optimization", title: "Performance Optimization" },
      ],
    }],
  },
  {
    slug: "backend",
    title: "Backend",
    description: "Design secure and reliable server-side applications.",
    technologies: [{
      slug: "nodejs",
      title: "Node.js",
      description: "Practice REST APIs, security, validation, and error handling.",
      topics: [
        { level: "advanced", slug: "rest-api-fundamentals", title: "REST API Fundamentals" },
        { level: "advanced", slug: "password-security", title: "Password Security" },
        { level: "advanced", slug: "authentication", title: "Authentication" },
        { level: "advanced", slug: "resource-authorization", title: "Resource Authorization" },
        { level: "advanced", slug: "role-based-authorization", title: "Role-Based Authorization" },
        { level: "advanced", slug: "request-validation", title: "Request Validation" },
        { level: "advanced", slug: "centralized-error-handling", title: "Centralized Error Handling" },
      ],
    }],
  },
  {
    slug: "database",
    title: "Database",
    description: "Store, relate, and query application data safely.",
    technologies: [{
      slug: "mysql",
      title: "MySQL",
      description: "Practice persistence, joins, indexing, and transactions.",
      topics: [
        { level: "advanced", slug: "mysql-persistence", title: "MySQL Persistence" },
        { level: "advanced", slug: "relationships-and-joins", title: "Relationships and JOINs" },
        { level: "advanced", slug: "query-optimization", title: "Indexes and Query Optimization" },
        { level: "advanced", slug: "transactions-and-concurrency", title: "Transactions and Concurrency" },
      ],
    }],
  },
];

export function getTechnology(areaSlug, technologySlug) {
  const area = assignmentCatalog.find((item) => item.slug === areaSlug);
  const technology = area?.technologies.find((item) => item.slug === technologySlug);
  return area && technology ? { area, technology } : null;
}

export function getAssignmentPath(assignment) {
  return `/assignments/${assignment.area}/${assignment.technology}/${assignment.topic}/${assignment.slug}`;
}
